defaults:
  - config: config
  - override hydra/sweeper: optuna
  - _self_

hydra:
    sweeper:
      n_trials: 25
      direction: "minimize"
      n_jobs: 1

      sampler:
        _target_: optuna.samplers.TPESampler
        seed: 42
        n_startup_trials: 5

      params:
        training.learning_rate: tag(log, interval(1e-6, 1e-2))
        training.alpha: interval(0.01, 1.0)
        training.temperature: interval(1.0, 5.0)
        training.total_steps: 20000
        training.warmup_steps: 1000
